crates/base_ops/Cargo.toml
crates/base_ops/src/baseops.rs
crates/base_ops/src/import/csv.rs

Finally, I reproduce the base benchmarks with ClickHouse.
It shows `tensorbase` outperforms `ClickHouse` by 1.x - 2.x.   
Yet there are some bugs to fix for others to try `tensorbase`.
Results:
```
[query]>select count(trip_id - 100  )  from  nyc_taxi;
kernel exec time: 225.380904ms
843646163758811010
query response time: 225.492269ms
:) select sum(trip_id -100 )  from  nyc_taxi;  -- 3 partition
SELECT sum(trip_id - 100)
FROM nyc_taxi
Query id: e9eb9ccf-8f47-42d7-9fe6-89e10faaec19
┌─sum(minus(trip_id, 100))─┐
│       843673733667788365 │
└──────────────────────────┘
1 rows in set. Elapsed: 0.748 sec. Processed 1.30 billion rows, 5.20 GB (1.74 billion rows/s., 6.95 GB/s.)
```
datas in ClickHouse, 3 partitions
```
>  du -sh data/datasets/nyc_taxi/*
4.1G    data/datasets/nyc_taxi/0_3_3558_5 …
```

base_ops: use crate csv to replace simdcsv

---

crates/base/src/datetimes.rs
crates/base/src/hash.rs
crates/base/src/mmap.rs
crates/engine/src/datafusions.rs
crates/engine/src/lib.rs
crates/engine/src/types.rs
crates/lightjit/src/builtins.rs
crates/meta/src/confs.rs
crates/meta/src/store/parts.rs
crates/meta/src/store/sys.rs
crates/meta/src/types.rs
crates/runtime/src/ch/blocks.rs
crates/runtime/src/ch/messages.rs
crates/runtime/src/errs.rs
crates/runtime/src/lib.rs
crates/runtime/src/mgmt.rs
crates/runtime/src/read.rs

This mostly removed unused stuff that was generating warnings. 
The two interesting changes are in `crates/runtime/src/mgmt.rs`
Line 88 we don't need the `= None` part since the compiler can guarantee that it gets assigned the correct type in the following if statements.
```
let mut conf_opt: Option<Conf> = None;
```
Line 963 the counter got moved outside of the for-loop
```
ic += 1;
```

fix warnings

---

crates/meta/src/types.rs
crates/tests_integ/tests/sanity_checks.rs

Small update. I commented out the `system numbers` test since datafusion doesn't currently support it. 
I also fixed a couple unused variable warnings that I forgot to fix in my last PR.

Ignore unused tests & variables

---

arrow-datafusion/arrow/src/array/array_primitive.rs
arrow-datafusion/arrow/src/array/transform/mod.rs
arrow-datafusion/arrow/src/datatypes/numeric.rs
arrow-datafusion/arrow/src/temporal_conversions.rs
arrow-datafusion/datafusion/src/logical_plan/expr.rs
arrow-datafusion/datafusion/src/logical_plan/mod.rs
arrow-datafusion/datafusion/src/physical_plan/datetime_expressions.rs
arrow-datafusion/datafusion/src/physical_plan/expressions/binary.rs
arrow-datafusion/datafusion/src/physical_plan/expressions/coercion.rs
arrow-datafusion/datafusion/src/physical_plan/expressions/nullif.rs
arrow-datafusion/datafusion/src/physical_plan/functions.rs
arrow-datafusion/datafusion/src/physical_plan/group_scalar.rs
arrow-datafusion/datafusion/src/physical_plan/hash_aggregate.rs
arrow-datafusion/datafusion/src/scalar.rs
arrow-datafusion/datafusion/src/sql/planner.rs
arrow-datafusion/datafusion/tests/sql.rs

This pull request does three things:
- Adds additional support to arrow for the new `date16` type
- Adds support for the `date16` type to DataFusion
- Adds a `to_date()` builtin to DataFusion that converts a string `to_date("YYYY-MM-DD")` to a `Date16`
Related: #84

Support to_date() builtin

---

crates/meta/src/store/sys.rs

As I ran the unit tests via this command
```bash
cargo test --exclude 'arrow*' --exclude datafusion --exclude parquet --workspace -- --test-threads=1
```
Except the tests failure due to hard coded paths, I still got this error in `store::sys::unit_tests::sanity_checks`
```
---- store::sys::unit_tests::sanity_checks stdout ----
tmp_dir: /tmp
to remove the existed tmp_mdb_path: /tmp/m0 
dbid: 0
k: test_db_01.test_2020-12-21, v: [1, 0, 0, 0, 0, 0, 0, 0]
k: test_db_01.test_2020-12-21.c_as_df_gh0, v: [2, 0, 0, 0, 0, 0, 0, 0]
k: test_db_01.test_2020-12-21.c_as_df_gh1, v: [3, 0, 0, 0, 0, 0, 0, 0]
k: test_db_01.test_2020-12-21.c_as_df_gh2, v: [4, 0, 0, 0, 0, 0, 0, 0]
k: test_db_01.test_2020-12-21.c_as_df_gh3, v: [5, 0, 0, 0, 0, 0, 0, 0]
k: …
```

fix test `store::sys::unit_tests::sanity_checks`

---

crates/meta/src/errs.rs
crates/meta/src/types.rs

This PR added support of `Decimal32` and `Decimal64` shortcut type, and also added checks for the precision and scale of the `Decimal` type.
resolved #61

support `Decimal32` and `Decimal64` shortcut type

---

crates/base/src/strings.rs
crates/engine/src/datafusions.rs
crates/lang/src/bql.pest
crates/lang/src/parse.rs
crates/meta/Cargo.toml
crates/meta/src/errs.rs
crates/meta/src/store/parts.rs
crates/meta/src/types.rs
crates/runtime/src/ch/blocks.rs
crates/runtime/src/write.rs
crates/tests_integ/tests/sanity_checks.rs

Added the basic support `BqlType::FixedString`. It is able to create tables with `FixedString`-typed columns, insert into or query from such tables.
```
TensorBase :) create table test_fixed (s FixedString(10)) engine = BaseStorage;
CREATE TABLE test_fixed
(
s FixedString(10)
)
ENGINE = BaseStorage
Ok.
0 rows in set. Elapsed: 0.014 sec. 
TensorBase :) insert into test_fixed values ('test')
INSERT INTO test_fixed VALUES
Ok.
1 rows in set. Elapsed: 0.008 sec. 
TensorBase :) select s from test_fixed
SELECT s
FROM test_fixed 
┌─s────┐
│ test │
└──────┘
1 rows in set. Elapsed: 0.019 sec. 
```
However, queries with `where` clauses such as `select col from tab where col = 'value'` is not supported due to the same reason with #98.
TODO: it might …

prototype of support for `FixedString` type

---

crates/meta/src/store/parts.rs
crates/runtime/src/mgmt.rs
crates/tests_integ/tests/sanity_checks.rs

`truncate table` doesn't change the `PartStore` metadata. So if we `truncate table` and `insert into table`, we will get the wrong result.
This PR makes it right.

fix wrong result in truncate table

---

arrow-datafusion/ballista/rust/scheduler/src/planner.rs
arrow-datafusion/ballista/rust/scheduler/src/state/mod.rs
crates/base/proc_macro/src/lib.rs
crates/base/src/mem.rs
crates/lang/src/parse.rs
crates/lightjit/src/builtins.rs
crates/lightjit/src/jit.rs
crates/meta/src/store/parts.rs
crates/meta/src/store/sys.rs
crates/runtime/src/ch/messages.rs
crates/tests_integ/ch_client/src/client.rs
crates/tests_integ/ch_client/src/errors.rs
crates/tests_integ/ch_client/src/pool/builder.rs
crates/tests_integ/ch_client/src/pool/mod.rs
crates/tests_integ/ch_client/src/pool/recycler.rs
crates/tests_integ/ch_client/src/protocol/block.rs
crates/tests_integ/ch_client/src/protocol/column.rs
crates/tests_integ/ch_client/src/types/mod.rs

Fix some typos and clippy lints like:
```
warning: this could be a `const fn`
--> crates/tests_integ/ch_client/src/types/mod.rs:112:5
|
112 | /     pub fn is_nullable(&self) -> bool {
113 | |         (self.flag & FIELD_NULLABLE) == FIELD_NULLABLE
114 | |     }
| |_____^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_fn
warning: this expression borrows a reference (`&std::string::String`) that is immediately dereferenced by the compiler
--> crates/meta/src/store/sys.rs:678:50
|
678 |                 let cid = self.new_col(&dn, &tn, &colname)?;
|                                                  ^^^^^^^^ help: change this to: `colname`
|
= help: for further information visit …
```

Fix some typos and clippy lints

---

.github/workflows/base_integ_sanity_checks.yml
crates/arrow/Cargo.toml
crates/arrow/src/datatypes/datatype.rs
crates/base/Cargo.toml
crates/base/src/datetimes.rs
crates/base/src/errs.rs
crates/base/src/lib.rs
crates/datafusion/src/lib.rs
crates/datafusion/src/physical_plan/clickhouse.rs
crates/datafusion_tests/Cargo.toml
crates/datafusion_tests/tests/clickhouse.rs
crates/engine/src/types.rs
crates/engine/tests/df_tests.rs
crates/lightjit/src/builtins.rs
crates/meta/src/confs.rs
crates/runtime/Cargo.toml
crates/runtime/src/ch/messages.rs
crates/runtime/src/mgmt.rs
crates/runtime/src/read.rs
crates/runtime/src/write.rs
crates/tests_integ/Cargo.toml
crates/tests_integ/tests/sanity_checks.rs

As the discussion in #27, this PR adds a global default timezone with an offset.
What this PR does:
- when timestamps are parsing from string, the offset subtracts,
- when timestamps are interpreted as days/hours via the `toDayOfMonth/toHour` functions etc., the offset is added.
What this PR does **NOT** yet:
- when timestamps are displayed as a string, the offset is NOT added yet.

basic support of default timezone

---

docs/CONTRIBUTING.md

I suggest we keep [these commit conventions](https://www.conventionalcommits.org/en/v1.0.0/), which might make the commit messages more meaningful and easy to classified and located (with a type and an optional scope).
See the doc update for more details.

DOCS: update the commit conventions

---

crates/engine/src/datafusions.rs
crates/tests_integ/tests/sanity_checks.rs

If we use `select * `  with other column conditions, we will get the wrong result.
For example:
```
create table test (a UInt64, b UInt64) ENGINE = BaseStorage
insert into test values (1,1),(2,2)
TensorBase :) select * from test where b=1
SELECT *
FROM test
WHERE b = 1
Query id: 03beb4cb-b5e3-4318-b154-a39f9950108e
┌─b─┐
│ 1 │
└───┘
```
This PR fix it.

fix `select *` logical error 

---

crates/base/src/datetimes.rs
crates/datafusion/src/physical_plan/clickhouse.rs
crates/datafusion/src/physical_plan/functions.rs
crates/datafusion_tests/tests/clickhouse.rs

@jinmingjian @pandaplusplus 
After #173, the macros in `clickhouse.rs` in A-DF shows to become too complicated. So I simplified the wrapping macro to contain only a array downcast process.

REFACTOR(datafusion): simplify the `wrap_datetime_fn` macro

---

crates/lang/src/bql.pest
crates/lang/src/parse.rs

As #172, sql-parser support function bool-valued in where clause, but tb's pest parse not support this. 
three solutions(bql.pest): 
1.  modify `comp_expr_cmp`. ( `comp_expr_cmp = { comp_expr_cmp_operand ~( comp_op ~ comp_expr_cmp_operand)? }`)
2.  add `expr` after `comp_expr_cmp` in `comp_expr` statment
3.  add `func_call_expr` after `comp_expr_cmp` in `comp_expr` statment
I think third one is better, it has smaller impact(just function call) than others.

support bool-valued func in where clause

---

crates/base/proc_macro/src/lib.rs
crates/base/src/datetimes.rs
crates/base/src/mmap.rs
crates/base/src/strings.rs
crates/base/tests/proc_macro_tests.rs
crates/runtime/src/mgmt.rs

1. use libc::tmpfile() create tempfile instead of string concat of std::env::temp_dir()
file created by tempfile() would **automatically deleted** when it is closed or the program terminates.
https://github.com/tensorbase/tensorbase/blob/043c337edd0d898031f7ba3facfaba888beb1d43/crates/base/src/mmap.rs#L109-L113
2. Fix some clippy lints
eg. [lint unseparated_literal_suffix](https://rust-lang.github.io/rust-clippy/master/index.html#unseparated_literal_suffix)
we should write `0_u8` rather than `0u8`

enhance tempfile created on test case test_mm_file_ro

---

crates/base/src/datetimes.rs
crates/base/src/fuzz.rs
crates/client/src/client.rs
crates/client/src/prelude.rs
crates/client/src/protocol/block.rs
crates/client/src/protocol/column.rs
crates/client/src/types/mod.rs
crates/engine/Cargo.toml
crates/engine/src/errs.rs
crates/engine/src/lib.rs
crates/engine/src/remote.rs
crates/lang/src/parse.rs
crates/runtime/Cargo.toml
crates/runtime/src/ch/blocks.rs
crates/runtime/src/errs.rs
crates/runtime/src/mgmt.rs
crates/runtime/src/read.rs
crates/server/src/server.rs
crates/server/tests/confs/base.conf
crates/tests_integ/tests/sanity_checks.rs

Related #109 let it work first，and we need more optimization, for example, the best approach is to unify the server and client block definitions to avoid conversions. 
We can support `insert into select a from remote('127.0.0.1:9000', test_a) limit 10` now to insert remote data, then we can support `insert into Function remote`  semantic next step.

FEAT(engine,client,lang,runtime,server): simple remote query function impl

---

crates/base/src/datetimes.rs
crates/client/src/protocol/column.rs
crates/datafusion/src/physical_plan/clickhouse.rs
crates/datafusion_tests/tests/clickhouse.rs
crates/tests_integ/tests/sanity_checks.rs

Note: `toDateTime` with timezone is not supported yet.
To support timezone in `toDateTime`, there might be a little change in A-DF, because timezone in value will be introduced (currently timezone is only supported in schema), and the signatures or return types should be different with different timezones.

Support `toDatetime`

---

crates/base/src/mmap.rs
crates/meta/src/store/parts.rs
crates/runtime/src/write.rs
crates/test_utils/src/lib.rs

Hi all!
I'm using MacOS for development, so I tried to port Tensorbase to MacOS . I've managed to pass all the unit tests on my MacOS 10.15.7. It turns out that not too many changes are needed and they are mostly due to libc API incompatibilities. 
Three files are changed:
- mmap.rs: I removed m_mremap() function because MacOS doesn't have mremap() system call. This function is in fact dead code so removing it does not have any impact.
- part.rs: MacOS's open() call doesn't have the `mode` argument , so I used chmod() to change the file's access mode after file opening. The `O_NOATIME` flag is not present in MacOS, so I just removed it. **I'm not sure if this will cause any side effects.**
- write.rs: MacOS doesn't have the falllocate() system call. I wrote a custom fallocate() function …

FEAT(platform): Add MacOS support

---

crates/base/Cargo.toml
crates/base/src/errs.rs
crates/base/src/eval.rs
crates/base/src/lib.rs
crates/engine/src/datafusions.rs
crates/engine/tests/df_tests.rs
crates/lang/src/bql.pest
crates/lang/src/errs.rs
crates/lang/src/parse.rs
crates/meta/src/store/parts.rs
crates/meta/src/store/sys.rs
crates/runtime/src/mgmt.rs

I am not sure if there is still a problem with the implementation.
* not support `datetime` prune yet.
* only support easy partition prune base on values.
relate issue: #55

REFACTOR(parse, storage):  support basic partition prune

---

crates/lang/src/parse.rs
crates/tests_integ/tests/sanity_checks.rs

if there is no hit partition key in parse where condition, we should use all partitions.
wrong case:
```
create table t (a UInt32, b UInt32)engine=BaseStorage partition by a
insert into t values (1,1),(2,2)
TensorBase :) select a from t where b = 1
SELECT a
FROM t
WHERE b = 1
Query id: 7803f9da-c4e3-4dae-bebd-4db4a0de3939
Ok.
0 rows in set. Elapsed: 0.005 sec. 
```

FIX(lang):should use all partitions if partition expr isn't hit

---

docs/get_started_developers.md
docs/get_started_users.md

I tried to make TensorBase support the execution of multiple SQL statements, and finally found that clickhouse-client only needs to set a parameter -n.
So I modified the get_started docs. 
I think maybe users should be more accustomed to executing multiple SQL statements with ";".
It should be safe to do so, because #107 has already been completed.

[DOCS] update get started docs

---

crates/engine/src/datafusions.rs
crates/lang/src/parse.rs
crates/meta/src/store/parts.rs
crates/tests_integ/tests/sanity_checks.rs

wrong case:
```
create table t (a DateTime, b UInt32) engine=BaseStorage partition by toYear(a)
insert into t values ('2020-01-01:08:00:00',1),('2021-01-01:08:00:00',1)
TensorBase :) select * from t where toYear(a)<>2020
SELECT *
FROM t
WHERE toYear(a) != 2020
Query id: d986e108-ea6a-42dc-8d18-3f261fa6e516
Ok.
0 rows in set. Elapsed: 6.991 sec.
```
also fix a related test case in `integ_test`.

fix partition prune

---

crates/engine/src/datafusions.rs

In `setup_tables` function, `copas` in `copass` should have some length and `copass` should not be empty. This PR added check.

REFACTOR(engine): check copass in setup_tables

---

crates/lang/src/parse.rs

* Basically support `or` expr. And this will not deal with `or` `and` mixed situations at this time, in other words, multi-levels logical state.
* Basically support `between and` expr.
* add some unit tests for changes.

REFACTOR(lang): support or expr, between ... and ... expr

---

.github/workflows/base_checks.yml
crates/client/Cargo.toml
crates/client/src/protocol/column.rs
crates/lang/src/bql.pest
crates/lang/src/parse.rs
crates/runtime/src/ch/blocks.rs
crates/runtime/src/mgmt.rs
crates/runtime/src/read.rs
crates/server_mysql/Cargo.toml
crates/tests_integ/tests/sanity_checks.rs

FEAT(lang,client,lang,runtiem,integ_tests)` insert into remote 'FUNCTION' keyword support

FEAT(lang,client,lang,runtime,integ_tests) insert into remote related #109

---

crates/base/Cargo.toml
crates/base/src/errs.rs
crates/base/src/lib.rs
crates/base/src/uuid.rs
crates/client/src/protocol/value.rs
crates/datafusion/src/physical_plan/clickhouse.rs
crates/datafusion_tests/tests/clickhouse.rs
crates/engine/src/datafusions.rs
crates/meta/src/types.rs
crates/runtime/src/ch/blocks.rs
crates/tests_integ/tests/sanity_checks.rs

Using arrow type `FixedSizedBinary(16)` works fine for UUID, but there are also some problems.
The UUID type returned from TB will be displayed in bytes, instead of an encoded string of length 36, And when do `Block::try_from(record_batch)`, the A-DF type `FixedSizedBinary(16)` will be translated to `BqlType::FixedString(16)` instead of `UUID`.
I also tried adding a `UUID` type in arrow, but it has brought more problems. Since `FixedSizedBinary` in A-DF directly stores its data in generally the `ArrayData` with data type in it. It is not easy to construct a `UUID` type to incorporate a `FixedSizedBinary` in it, keeping anything else in place and only changing the data type.
I think the `BqlType` in our scheme might be needed when converting arrow types back to bql types. Some data types …

Support UUID

---

crates/runtime/src/ch/blocks.rs
crates/runtime/src/ch/codecs.rs
crates/runtime/src/ch/messages.rs
crates/runtime/src/ch/protocol.rs
crates/runtime/src/lib.rs
crates/runtime/src/mgmt.rs
crates/runtime/src/mysql/mod.rs
crates/runtime/src/read.rs
crates/runtime/src/types.rs
crates/runtime/src/write.rs
crates/runtime/tests/system_tests.rs

Current runtime crate uses some definitions from its `ch` module. These include definitions for the data block (`Block`) and data structure for the connection state (`ConnCtx`). These definitions include data specific to the ClickHouse protocol, which makes it infeasible for other protocols, e.g., MySQL.
This PR removes this dependency by introducing two protocol-agnostic definitions:
* `struct BaseDataBlock`: This struct contains the exact data that TB's runtime requires, moving protocol-specific data to CH's `Block`.
* `trait BaseServerConn`: This trait contains the connection information that TB's runtime needs to know, e.g, current database id. CH's `ConnCtx` implements this trait.
The two commits in this PR changes a considerable amount of code changes. But most of them are …

REFACTOR(runtime): make runtime independent of CH protocol 

---

crates/meta/Cargo.toml
crates/meta/src/errs.rs
crates/meta/src/store/sys.rs
crates/meta/src/types.rs
crates/runtime/src/ch/messages.rs
crates/runtime/src/mgmt.rs
crates/runtime/src/read.rs
crates/runtime/tests/system_tests.rs

Current runtime code uses `BaseDataBlock` to represent query results, which is a simple wrapper around the `Vec<u8>` buffer. This straightforward representation does not enable easy element-wise data indexing, which is required for performing type conversion for the MySQL server.
This commit instead uses Arrow::RecordBatch to store query results, which provides good element-wise access API on top of the Arrow data format used by TB.
Note that our original `BaseDataBlock` is still useful as a "fast path". Where we do not need element-wise data access (e.g., INSERT queries), we can still use `BaseDataBlock` to directly store the data buffer.

REFACTOR(runtime): use RecordBatch to represent query results

---

.github/workflows/base_integ_sanity_checks.yml
crates/runtime/Cargo.toml
crates/runtime/src/lib.rs
crates/runtime/src/mysql/mod.rs
crates/server/Cargo.toml
crates/server/src/mysql_server.rs
crates/tests_integ/src/mysql_client.rs
crates/tests_integ/tests/common.rs
crates/tests_integ/tests/sanity_checks_mysql.rs

This implements a shim layer based on the msql-srv crate.
Currently the server is a minimum version whose aim is to support the MySQL client-server protocol. It currently only supports integer data types. Support for Float, Datatime, Date, Decimal and String will be added in future commits soon.
An example mysql_server and mysql_client is implemented.
Integration tests are also added for the MySQL server. These tests are adapted from the original sanity_checks.rs file.

add minimum MySQL protocol server

---

.github/workflows/base_checks.yml
.github/workflows/base_integ_sanity_checks.yml
Cargo.toml

This change uses Swatinem/rust-cache to store TB's dependencies (e.g., `./target` directory) between CI builds. This makes the CI process faster. From my own tests, the workflow execution time is reduced from ~12 minutes to ~7 minutes.
The `debug` build flag is disabled because doing so will significantly reduce the size of the cache, as well as make the compilation faster.
This change is inspired by a [blog post](https://matklad.github.io/2021/09/04/fast-rust-builds.html) on how rust-analyzer kept their CI time under 8 minutes.

CI: use cache to make CI builds faster

---

.github/workflows/base_integ_sanity_checks.yml
crates/tests_integ/tests/sanity_checks_mysql.rs

In the integ_test, we originally used `kill` to shut down the ClickHouse server before we start MySQL tests. This may cause data inconsistency issues because some metadata stored in `sled`'s pagecache may not have been flushed to disk when shut down happens. The previous CI failures is probably caused by this.
This commit cleans the schema and data directory before MySQL test starts to avoid data inconsistency problem. In the long term, a more graceful shutdown mechanism should be implemented for TB.
I ran the CI workflow on my fork for multiple times and the failures no longer happen now.

FIX(test, mysql_server): clean schema and data directory before running mysql server tests

---

crates/runtime/Cargo.toml
crates/runtime/src/mgmt.rs
crates/runtime/src/mysql/mod.rs
crates/tests_integ/tests/sanity_checks_mysql.rs

1. Use standard library `parse` methods to parse input floating point data.
2. Use `BigDecimal` crate to parse input decimal data. For input, this commit uses `BigDecimal` crate to parse and store Decimal data. For output, I manually did the type conversion between Decimal's underlying signed integer representation to the String output format.

FEAT(mysql_server): Add support for float and decimal types

---

crates/runtime/src/mgmt.rs
crates/runtime/src/mysql/mod.rs
crates/tests_integ/tests/sanity_checks_mysql.rs

This PR adds support for parsing literal strings in SQL queries. A parser function is added that is adapted `sqlparse`'s `tokenize_single_quoted_string()` function.
Besides, this PR adds support for converting TB's length-encoded string to MySQL string outputs.
Several more test cases in sanity_checks_mysql  can now get passed because of this change.

FEAT(mysql_server): add support for String type

---

crates/base/src/datetimes.rs
crates/runtime/src/mgmt.rs
crates/runtime/src/mysql/mod.rs
crates/tests_integ/tests/sanity_checks_mysql.rs

This commit enhances the support for parsing Date and Datetime literals in SQL queries. It also adds support for writing Date and Dateime values in MySQL outputs.
Three more test cases in sanity_checks_mysql can now get passed after this change.

FEAT(mysql_server): add support for Datetime and Date types
