tensorbase/tensorbase

crates/base/src/datetimes.rs, crates/base/src/hash.rs, crates/base/src/mmap.rs, crates/engine/src/datafusions.rs, crates/engine/src/lib.rs, crates/engine/src/types.rs, crates/lightjit/src/builtins.rs, crates/meta/src/confs.rs, crates/meta/src/store/parts.rs, crates/meta/src/store/sys.rs, crates/meta/src/types.rs, crates/runtime/src/ch/blocks.rs, crates/runtime/src/ch/messages.rs, crates/runtime/src/errs.rs, crates/runtime/src/lib.rs, crates/runtime/src/mgmt.rs, crates/runtime/src/read.rs
Reverts tensorbase/tensorbase#43
=> Revert "fix warnings"

crates/base/src/datetimes.rs, crates/base/src/hash.rs, crates/base/src/mmap.rs, crates/engine/src/datafusions.rs, crates/engine/src/lib.rs, crates/engine/src/types.rs, crates/lightjit/src/builtins.rs, crates/meta/src/confs.rs, crates/meta/src/store/parts.rs, crates/meta/src/store/sys.rs, crates/meta/src/types.rs, crates/runtime/src/ch/blocks.rs, crates/runtime/src/ch/messages.rs, crates/runtime/src/errs.rs, crates/runtime/src/lib.rs, crates/runtime/src/mgmt.rs, crates/runtime/src/read.rs
I had my git config misconfigured on the last pull request. This one is updated with correct information
=> git config update

crates/engine/src/datafusions.rs, crates/meta/src/types.rs, crates/runtime/src/ch/blocks.rs, crates/tests_integ/tests/sanity_checks.rs
Adds support for decimal type. Only 32bit decimal is supported right now.
Also fixed `basic_test_insert()` in the `tests_integ` crate.
Closes: #26
=> Support Decimal Type

docs/lang.md
Since date and decimal64 supported, update lang doc up to date.
Signed-off-by: grapebaba <281165273@qq.com>
=> Update lang doc up to date

.github/auto-merge.yml, .github/dependabot.yml, .github/workflows/dependabot_auto_merge.yml
Signed-off-by: Maizi Liao <liaomaizi@gmail.com>
=> add dependabot and automerge

docs/lang.md
Also reformat the doc a little bit.
Signed-off-by: Maizi Liao <liaomaizi@gmail.com>
=> Add more examples for TB SQL

docs/get_started_developers.md, docs/get_started_users.md
add examples about table creation, data insertion and aggregation.
Signed-off-by: Maizi Liao <liaomaizi@gmail.com>
=> add more examples for get_started docs

crates/engine/src/datafusions.rs, crates/engine/src/errs.rs, crates/engine/src/lib.rs, crates/lang/src/bql.pest, crates/lang/src/parse.rs, crates/meta/src/store/sys.rs
enable wildcard in select
Signed-off-by: Jin Mingjian <jin.phd@gmail.com>
=> fix issuee 94

README.md
I have made some grammatical improvements for the Readme
=> some grammatical improvements

crates/meta/src/store/parts.rs, crates/runtime/src/mgmt.rs, crates/tests_integ/tests/sanity_checks.rs
=> fix truncate table

crates/base/src/codec.rs, crates/base/src/errs.rs, crates/lang/src/bql.pest, crates/lang/src/parse.rs, crates/runtime/src/mgmt.rs, crates/tests_integ/tests/sanity_checks.rs
=> Table desc

crates/lang/src/bql.pest, crates/lang/src/parse.rs
=> tried to compatible for select-sql-end with a semicolon

crates/lang/tests/res/tpcds_20/query54.sql, crates/lang/tests/res/tpcds_full/query54.sql
fixed the benchmark-run-errors, updated the int-2-Int64
=> fixed the beachmark-run-error, updated the int to Int64

Cargo.toml, crates/datafusion/src/physical_plan/ch_fns.rs, crates/datafusion/src/physical_plan/functions.rs, crates/datafusion_tests/Cargo.toml, crates/datafusion_tests/tests/ch_fns.rs, crates/tests_integ/tests/sanity_checks.rs
=> support CH functions toMonth, toDayOfMonth

docs/get_started_developers.md, docs/get_started_users.md
Signed-off-by: wuaoxiang <os.popen@gmail.com>
=> add --compression=true for clickhouse-client version >= 21.5 to document

crates/runtime/src/ch/blocks.rs, crates/runtime/src/ch/messages.rs, docs/get_started_developers.md
Support the latest ClickHouse client without compression by default.
=> Fix the uncompressed raw packet data decoding error, #117

crates/base/src/datetimes.rs, crates/datafusion/src/physical_plan/clickhouse.rs, crates/datafusion_tests/tests/clickhouse.rs, crates/tests_integ/tests/sanity_checks.rs
- toQuarter
- toDayOfYear
- toDayOfWeek
- toHour
- toMinute
- toSecond
affects #131
=> support more CH date/time functions

crates/lang/src/bql.pest, crates/lang/src/parse.rs, crates/runtime/src/ch/blocks.rs, crates/runtime/src/ch/messages.rs, crates/runtime/src/mgmt.rs, crates/tests_integ/tests/sanity_checks.rs
@jinmingjian  It should meet the basic requirements in the PR now, please tell me if there is anything missing and issues.
=> support INSERT INTO .. SELECT #152

crates/datafusion/src/sql/planner.rs, crates/tests_integ/tests/sanity_checks.rs
Support Int16, Int32, Int64, Float32, Float64 based DF existed and mapped datatype.
=> support CAST expression #158

crates/datafusion/src/physical_plan/clickhouse.rs, crates/datafusion/src/physical_plan/functions.rs, crates/datafusion_tests/tests/clickhouse.rs, crates/tests_integ/tests/sanity_checks.rs
finished related #159, and implement the toDate(LargeUtf8), toDate(Utf8), toDate(Int64) function in addition.
=> Todate impl

crates/client/Cargo.toml, crates/client/src/client.rs, crates/client/src/compression/mod.rs, crates/client/src/pool/mod.rs, crates/client/src/protocol/command.rs, crates/client/src/protocol/decoder.rs, crates/tests_integ/Cargo.toml
=> REFACTOR(client, tests_integ) Update tokio requirement from 0.2 to 1.0

crates/base/tests/proc_macro_tests.rs
=> TEST(base): relax timer test threshold

.github/workflows/base_checks.yml, crates/server_mysql/examples/psql_as_mysql.rs
=> FIX(server_mysql) fix the issue of postgres crate version

crates/meta/src/confs.rs, crates/runtime/src/mgmt.rs, crates/runtime/src/read.rs, crates/server/src/server.rs, crates/server/tests/confs/base_with_remote_db.conf
=> FEAT(meta,runtime,server) initial remote ch/tb database config

crates/lang/src/bql.pest, crates/lang/src/parse.rs, crates/meta/src/confs.rs, crates/runtime/Cargo.toml, crates/runtime/src/mgmt.rs, crates/runtime/src/write.rs, crates/server/src/server.rs, crates/server/tests/confs/base_with_remote_db.conf
=> FEAT(lang,meta,runtime,server) remote connect mysql pool related #109

crates/engine/Cargo.toml, crates/engine/src/errs.rs, crates/engine/src/lib.rs, crates/engine/src/mysql.rs, crates/engine/src/remote.rs, crates/runtime/src/errs.rs, crates/runtime/src/mgmt.rs, crates/runtime/src/read.rs, crates/server/tests/confs/base_with_remote_db.conf
=> FEAT(engine,runtime) support to remote query mysql table related #109

crates/engine/src/datafusions.rs, crates/engine/src/remote.rs, crates/runtime/src/ch/blocks.rs, crates/runtime/src/mgmt.rs, crates/runtime/src/read.rs
=> FEAT(engine,runtime) nullable(typename) support for tb query related #236

crates/runtime/src/ch/blocks.rs
=> FEAT(engine,runtime) nullable(typename) support from remote ch/tb #236

crates/engine/src/mysql.rs
=> FEAT(engine) support mysql unsigned column

crates/engine/src/mysql.rs, crates/engine/src/remote.rs, crates/runtime/src/read.rs
=> FIX(runtime, engine) fix the mysql decimal precision and scale

crates/engine/src/mysql.rs, crates/runtime/src/read.rs
=> FEAT(engine, runtime) support MySQL blob to TB String type

.github/workflows/base_checks.yml, .github/workflows/base_integ_sanity_checks.yml, crates/tests_integ/Cargo.toml, crates/tests_integ/src/sql_test_runner.rs, crates/tests_integ/tests/common.rs, crates/tests_integ/tests/sanity_checks.rs
=> CI: mysql/clickhouse install

crates/engine/src/mysql.rs, crates/tests_integ/tests/common.rs, crates/tests_integ/tests/sanity_checks.rs
=> FEAT(engine) support BIT , JSON , SET, GEOMETRY of MySQL

crates/tests_integ/tests/sanity_checks_mysql.rs
Happy Mid-Autumn Festival🥮!
This is the last of a series of patches to support TB's built-in data types on the MySQL protocol server.
It turns out that there's no need to change MySQL server's code to support UUID types, so I just enabled the test.
=> TEST(mysql_server): add test for UUID data type
